- name: installing ngnix
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: installing nginx package
    anisble.builtin.package:
      name: nginx
      state: present
  - name: startuing the nginx package
    anisble.builtin.service
      name: nginx
      state: start
      enabled: yes